spring:
  # --- Security / OIDC config ---
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${COGNITO_ISSUER_URI}
  # --- Database config ---
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/changelog-main.yaml
    enabled: true

mybatis:
  mapper-locations: classpath*:mybatis/mappers/*Mapper.xml
  type-aliases-package: com.t2.screening.tenisu.domain
  type-handlers-package: com.t2.screening.tenisu.infrastructure.mybatis.typehandler
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    use-generated-keys: true
    auto-mapping-behavior: full


management:
  endpoints:
    web:
      base-path: '/'            # puts actuator under root
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: never     # do not leak component details to the public
      probes:
        enabled: true

logbook:
  predicate:
    exclude:
      - path: '/info'
      - path: '/health'
      - path: '/env'
      - path: '/configprops'

logging.level:
  org.zalando.logbook: trace