### Get token via OAUTH2 (client credentials compatible with cognito & KC)
POST {{auth_server_url}}
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{client_basic_auth}}

grant_type=client_credentials&scope=tenisu-api/read

> {%client.global.set("auth", response.body); %}


### Info request
GET {{base_url}}/info
Authorization: Bearer {{auth.access_token}}

### Health request
GET {{base_url}}/health
Authorization: Bearer {{auth.access_token}}

### Environment request
GET {{base_url}}/env

### Config props request
GET {{base_url}}/configprops

### Find all players
GET {{base_url}}/players
Authorization: Bearer {{auth.access_token}}

### Find one player
GET {{base_url}}/players/103
Authorization: Bearer {{auth.access_token}}

### Create valid player
POST {{base_url}}/players
Authorization: Bearer {{auth.access_token}}
Content-Type: application/json

{
  "firstname": "titi",
  "lastname": "toto",
  "sex": "M",
  "countryCode": "FRA",
  "picture": "http://url.com/format",
  "data": {
    "rank": 10,
    "points": 100,
    "weight": 75500,
    "height": 170,
    "age": 30,
    "last": [1, 1, 0, 0, 1]
  }
}

### Find statistics
GET {{base_url}}/statistics
Authorization: Bearer {{auth.access_token}}

###